name: DATG Cloud Simulation Engine

# Ye pipeline tab chalegi jab tum code change karoge ya manually button dabaoge
on:
  push:
    branches: [ main, master ]
  workflow_dispatch: 

jobs:
  run-simulation:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Server par tumhara code fetch karna
    - name: Checkout Code
      uses: actions/checkout@v4

    # Step 2: Server par Python install karna
    - name: Setup Python Environment
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    # Step 3: Tumhara Simulation Engine Run karna
    - name: Execute Traffic Simulator
      run: python simulation.py

    # Step 4: Jo CSV Data log banega, usko server se nikal kar tumhe dena
    - name: Upload Telemetry Dataset (Artifact)
      uses: actions/upload-artifact@v4
      with:
        name: traffic-dataset
        path: traffic_telemetry.csv
        
